// <auto-generated />
namespace ASPNetFramework_Angular7_EF.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201905270804435_AddedItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
